# Generated by Django 5.2.13 on 2026-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('grade', models.IntegerField(default=11)),
                ('stream', models.CharField(default='science')),
            ],
        ),
    ]
